apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:55:58Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2425"
  uid: f0a572d0-a128-42ae-9c77-63b0d68e032b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.152.147
  clusterIPs:
  - 10.96.152.147
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30804
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
